/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_root_habbits_jni_HelloNDK */
//用javah命令编译之后自动生成的jni头文件
//定位到main目录下，此目录下有个java文件夹，存放源代码，有个jni文件夹，存放生成的c文件
//javah -d jni -classpath ..\..\build\intermediates\classes\debug com.....(包名 + 类名)
#ifndef _Included_com_example_root_habbits_jni_HelloNDK
#define _Included_com_example_root_habbits_jni_HelloNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_root_habbits_jni_HelloNDK
 * Method:    getCLangString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_root_habbits_jni_HelloNDK_getCLangString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
